### ISSUE TITLE
image + button bug in the editor

### ISSUE THREAD

**Issue by decoejz** [IMCreatorLTD/QA-Testing#11]
This bug just happen in the editor part, the preview work whenever I try it.

The bug:
When I add a button and choose "scroll to" and then select to do the background been the button as well, the image just disappear (in the preview part the button and the image work). Then I tried to delete the button to see if the image come back and it did not happend. So I tried to add the button again, and when I did it, the image went down and still did not appear.

The image only appears if the page is reloaded

![foto 1](https://cloud.githubusercontent.com/assets/18471780/24658625/edb73a30-1952-11e7-8c53-62970437777a.PNG)
![foto 2](https://cloud.githubusercontent.com/assets/18471780/24658626/edb8017c-1952-11e7-8702-1f911b4b1a9d.PNG)

**Comment by boozi2** [comment]
Could not reproduce :(
